apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-udpv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-udpv@sha256:1a0356c67f7bc3c4df62d6914b42da5704b82207f2dbd07b4aad202dd1778b03
        name: my-nodejs
        resources: {}
status: {}
